// Writes dist/sw.js: a service worker that precaches the whole app shell (including the WASM engine and the
// fonts) so File Refragmenter installs and works offline. The cache name changes whenever any file changes.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dist = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist');
const files = [];
const walk = (dir) => {
  for (const f of readdirSync(dir)) {
    const p = path.join(dir, f);
    if (statSync(p).isDirectory()) walk(p);
    else files.push(p);
  }
};
walk(dist);
const hash = createHash('sha256');
const urls = [];
for (const f of files.sort()) {
  const rel = path.relative(dist, f).split(path.sep).join('/');
  if (rel === 'sw.js' || rel === '_headers' || rel.startsWith('bundled/') && !rel.endsWith('manifest.json')) continue;
  hash.update(rel);
  hash.update(readFileSync(f));
  urls.push('./' + rel);
}
urls.push('./');
const version = hash.digest('hex').slice(0, 12);
const sw = `// Generated by scripts/postbuild.mjs
const CACHE = 'refragmenter-${version}';
const PRECACHE = ${JSON.stringify(urls, null, 1)};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => (k.startsWith('refragmenter-') || k.startsWith('jpegit-')) && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== location.origin) return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(e.request).then((res) => {
        // bundled photos are cached lazily, the first time they are used
        if (res.ok && url.pathname.includes('/bundled/')) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(e.request, copy));
        }
        return res;
      }).catch(() => (e.request.mode === 'navigate' ? caches.match('./index.html') : Response.error()));
    }),
  );
});
`;
writeFileSync(path.join(dist, 'sw.js'), sw);
console.log(`sw.js: ${urls.length} files precached (cache ${version})`);
